### ISSUE TITLE
Images made with conformal

### ISSUE THREAD

**Issue by adammaj1** [mjg/conformal#1]
Hi. Thx for the script
Here are images made with it : 
https://commons.wikimedia.org/wiki/File:Domain_coloring_x2-1_x-2-i_x-2-i_d_x2%2B2%2B2i.xcf
https://commons.wikimedia.org/wiki/File:Unit_circle_domain_coloring.png

I have put code also there
Is it OK 

Adam

**Comment by mjg** [comment]
Yes, it's OK (I guess wikimedia wants it for purposes of recreation). It's best to link here (github) only, not my work site.

Great choice of colouring on the rational function btw. Do you think it's worthwhile to add the "polar grid" optionally as an extra layer, rather than by playing tricks with the gradient?

**Comment by adammaj1** [comment]
Code is for not only for recreation of the image but also for:

-  learning programing

- checking if the image is correct


There is a category : 
https://commons.wikimedia.org/wiki/Category:Images_including_source_code_in_their_description


Polar grid is OK.

**Comment by mjg** [comment]
Thanks, closing for now.
